package io.openfuture.chain.core.exception.model

enum class ExceptionType {
    INCORRECT_HASH,
    INCORRECT_ADDRESS,
    INCORRECT_DELEGATE_KEY,
    ALREADY_DELEGATE,
    ALREADY_VOTED_FOR_DELEGATE,
    ALREADY_SENT_VOTE,
    INSUFFICIENT_BALANCE,
    INSUFFICIENT_ACTUAL_BALANCE,
    INCORRECT_SIGNATURE,
    INCORRECT_VOTES_COUNT,
    INVALID_CONTRACT,
    CONTRACT_METHOD_NOT_EXISTS
}