# DATABASE
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5434/open_chain_3
spring.datasource.username=postgres
spring.datasource.password=123456

# Logging
logging.level.io.openfuture.chain=INFO

# RPC
server.port=8083

# NODE
node.port=9193
node.root-nodes=localhost:9191,localhost:9192

node.config-path=configs/config-3.json