FROM openjdk:8-jre

RUN apt-get update && \
    apt-get install -y \
        sqlite3 \
        libsqlite3-dev

RUN echo "alias sql='sqlite3 chain.db'" >> ~/.bashrc && \
    echo "alias b='sqlite3 chain.db SELECT\ *\ FROM\ blocks;'" >> ~/.bashrc && \
    echo "alias mb='sqlite3 chain.db SELECT\ *\ FROM\ main_blocks;'" >> ~/.bashrc && \
    echo "alias gb='sqlite3 chain.db SELECT\ *\ FROM\ genesis_blocks;'" >> ~/.bashrc && \
    echo "alias t='sqlite3 chain.db SELECT\ *\ FROM\ transactions;'" >> ~/.bashrc && \
    echo "alias vt='sqlite3 chain.db SELECT\ *\ FROM\ vote_transactions;'" >> ~/.bashrc && \
    echo "alias dt='sqlite3 chain.db SELECT\ *\ FROM\ delegate_transactions;'" >> ~/.bashrc && \
    echo "alias tt='sqlite3 chain.db SELECT\ *\ FROM\ transfer_transactions;'" >> ~/.bashrc && \
    echo "alias rt='sqlite3 chain.db SELECT\ *\ FROM\ reward_transactions;'" >> ~/.bashrc && \
    echo "alias ut='sqlite3 chain.db SELECT\ *\ FROM\ u_transactions;'" >> ~/.bashrc && \
    echo "alias uvt='sqlite3 chain.db SELECT\ *\ FROM\ u_vote_transactions;'" >> ~/.bashrc && \
    echo "alias udt='sqlite3 chain.db SELECT\ *\ FROM\ u_delegate_transactions;'" >> ~/.bashrc && \
    echo "alias utt='sqlite3 chain.db SELECT\ *\ FROM\ u_transfer_transactions;'" >> ~/.bashrc && \
    echo "alias w='sqlite3 chain.db SELECT\ *\ FROM\ wallets;'" >> ~/.bashrc && \
    echo "alias d='sqlite3 chain.db SELECT\ *\ FROM\ delegates;'" >> ~/.bashrc