---
- hosts: all
  remote_user: beksultan
  gather_facts: False
  tasks:
    - name: Remove openchain containers
      docker_container:
        name: "{{ item.name }}"
        state: absent
      with_items:
        - { name: openchain-2 }
    - name: Remove the embedded DB volumes
      docker_volume:
        name: "{{ item.name }}"
        state: absent
      with_items:
        - { name: db_volume-2 }
      when: true
    - name: Create a volumes for embedded DB
      docker_volume:
        name: "{{ item.name }}"
      with_items:
        - { name: db_volume-2 }
    - name: Re-create openchain containers
      docker_container:
        name: "{{ item.name }}"
        image: openplatform/chain:{{ image_tag }}
        state: started
        pull: yes
        env:
          RPC_PORT: "{{ item.app_port }}"
          NODE_PORT: "{{ item.api_port }}"
          KEY: '{ "externalPort" : {{ item.api_port }}, "externalHost" : "", "secret" : "{{ item.secret_key }}", "mode" : "FULL" }'
        published_ports:
          - "{{ item.app_port }}:{{ item.app_port }}"
          - "{{ item.api_port }}:{{ item.api_port }}"
        volumes:
          - "{{ item.db_volume }}:/root/db"
        restart_policy: always
      with_items:
        - { name: openchain-2, db_volume: db_volume-2, app_port: 9092, api_port: 9192, secret_key: "89f0667fe951f77fdce8d840683c34cfe21c5e17c6c4d55a5786903d137ef076" }
      no_log: True
    - name: Delete old images
      shell: docker image prune -a --force --filter "until=24h"
